### ISSUE TITLE
adding Github logo and link 

### ISSUE THREAD

**Issue by Nirvanjha2004** [SnipSavvy/SnipSavvy_Frontend#21]
Github logo should be present at the bottom near LinkedIN logo with a link attached to the github repo.

**Comment by Nirvanjha2004** [comment]
Please assign me this issue
![logo](https://github.com/SnipSavvy/SnipSavvy_Frontend/assets/140783287/dc168732-f268-474d-85e8-e9055e09037f)

**Comment by Khushi-Kaushik** [comment]
Please assign this issue to me

**Comment by sahilrohera10** [comment]
@Nirvanjha2004 Assigned .. go ahead ..
Good luck !!
