### ISSUE TITLE
Create a bottom to top button

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [SnipSavvy/SnipSavvy_Frontend#28]
Create a bottom to top button
@SnipSavvy i wanna work upon it under SSOC

**Comment by sahilrohera10** [comment]
@RamakrushnaBiswal assigned  .. go ahead 

Good luck !

**Comment by Debanjannnn** [comment]
Hi, @sahilrohera10 

I was looking for issues and came across this one (#28). After cloning the repository locally, it took me approximately 5 minutes to solve it. If it's okay with you, I can submit a PR to address this issue . I'm also attaching a clip 

Uploading SnipSavvy - Personal 2 - Microsoft_ Edge 2024-06-02 19-51-24.mp4…

**Comment by sahilrohera10** [comment]
@Debanjannnn didn't get the video!!

**Comment by sahilrohera10** [comment]
@RamakrushnaBiswal are you working on this issue ?

**Comment by Debanjannnn** [comment]
> @Debanjannnn didn't get the video!!

yeah there was a issue withe video before

**Comment by Debanjannnn** [comment]
> @RamakrushnaBiswal are you working on this issue ?

I solved the issue in my local system , so if you assign me the task then I'll put a pr.

**Comment by RamakrushnaBiswal** [comment]
@sahilrohera10 yes i am working upon it

**Comment by Debanjannnn** [comment]
> @sahilrohera10 my internship is going on so i cann't contribute right now .you can assign to @Debanjannnn

@RamakrushnaBiswal  thanks bud

**Comment by sahilrohera10** [comment]
@Debanjannnn u may raise the PR !

**Comment by Debanjannnn** [comment]
> @Debanjannnn u may raise the PR !

done

**Comment by sahilrohera10** [comment]
Commented ! @Debanjannnn

**Comment by Debanjannnn** [comment]
> Commented ! @Debanjannnn

sure I'll change the file name

**Comment by Debanjannnn** [comment]
@sahilrohera10 please check the PR , I have renamed the files
