### ISSUE TITLE
Unresponsive design and Poor image quality in mobile view

### ISSUE THREAD

**Issue by areycruzer** [SnipSavvy/SnipSavvy_Frontend#29]
![Screenshot_20240601_163807](https://github.com/SnipSavvy/SnipSavvy_Frontend/assets/84120511/9b5a8ae4-4cb7-4e1f-8ac0-5d4e00605e61)
![Screenshot_20240601_163505](https://github.com/SnipSavvy/SnipSavvy_Frontend/assets/84120511/3a363ba3-7f1a-45b5-b106-b2d9c1fff259)

Don't know if it's worthy but bug is bug

**Comment by sahilrohera10** [comment]
ya, but we encourage you guys to focus more on the internal tool !!

**Comment by YASH-RAJ-HANS** [comment]
@areycruzer this tool is only for desktop view.
