### ISSUE TITLE
Add link tag in the Logo

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [SnipSavvy/SnipSavvy_Frontend#30]
![image](https://github.com/SnipSavvy/SnipSavvy_Frontend/assets/125277258/fdd9a630-f73a-45b9-8218-f2d21913b7e7)
And the link tag is redirecting to the home page

**Comment by Vrushti07** [comment]
Could I please be assigned this issue?

**Comment by tumansutradhar** [comment]
### I'd love to contribute to solving this problem for SSOC 2024!  I have the skills and experience necessary to tackle it.This problem looks really interesting! I'm confident I can contribute to a solution with my skills in Web Development. I'd be happy to help with SSOC 2024 for this one. I'm interested in contributing to SSOC 2024 for this problem.  If anyone is already working on it and needs help, I'd be happy to collaborate! I've already started brainstorming some ideas for solving this problem for SSOC 2024.  Would anyone be interested in working together on it?

**Comment by milanprajapati571** [comment]
I would love to contribute to the above-mentioned problem through my fluent skills in front-end development.
I request that you assign this task to me.
I will be able to complete this task within 3-4 days with the documentation

thank you for considering my response.

**Comment by tumansutradhar** [comment]
@sahilrohera10 I request that you assign this task to me.

**Comment by RamakrushnaBiswal** [comment]
@tumansutradhar  @milanprajapati571  @Vrushti07 are issue to main ne rise kiya hai🤔,you can find out more issues on the project.

**Comment by sahilrohera10** [comment]
@milanprajapati571 @Vrushti07 @tumansutradhar kindly go through the internal tool after login into the platform!
