### ISSUE TITLE
fixing feature button

### ISSUE THREAD

**Issue by sahuf2003** [SnipSavvy/SnipSavvy_Frontend#33]
On click feature button 
![image](https://github.com/SnipSavvy/SnipSavvy_Frontend/assets/127684377/fe61ecb3-d759-4d76-95aa-35268915c7f7)
It should navigate to this section 
![image](https://github.com/SnipSavvy/SnipSavvy_Frontend/assets/127684377/7a8de149-e69e-49a9-aebb-df7fbf6cad14)

**Comment by sahuf2003** [comment]
@SnipSavvy assign me this issue

**Comment by yash-25log** [comment]
@sahuf2003 The issue has already been assigned

**Comment by YASH-RAJ-HANS** [comment]
@sahuf2003 The issue has been already assigned. Kindly look for other issues.
