### ISSUE TITLE
Adding social media links in footer section

### ISSUE THREAD

**Issue by harikasayani** [SnipSavvy/SnipSavvy_Frontend#37]
I am SSOC'24 Contributor.
I observed that there is no social media links in footer section.
I want to add them.
Please assign me this task.

**Comment by Mallik0** [comment]
Hi there!
Social media links are important part of the website because they help the viewers reach out to us for more information therefore increasing the customer interaction, and i feel i can clearly resolve this issue, so kindly assign this issue to me @yash-25log

**Comment by yash-25log** [comment]
@Mallik0 @harikasayani Try to focus on the internal tool after signing in for SSOC.
