### ISSUE TITLE
Year needs to update dynamic in footer 

### ISSUE THREAD

**Issue by kapilG0** [SnipSavvy/SnipSavvy_Frontend#45]
![Screenshot_20240602_161707](https://github.com/SnipSavvy/SnipSavvy_Frontend/assets/59639410/8b5458fe-04c1-4fe0-83a4-329eee2c5356)

**Comment by kapilG0** [comment]
Hello @SnipSavvy please assign this issue to me under ssoc 24

**Comment by sahilrohera10** [comment]
Focus on the internal tool for SSOC

**Comment by sahilrohera10** [comment]
@kapilG0

**Comment by kapilG0** [comment]
> @kapilG0

Hello @sahilrohera10 sorry but not able to understand can you please elaborate

**Comment by sahilrohera10** [comment]
login to the platform and start contributing there, instead of landing page. @kapilG0

**Comment by kapilG0** [comment]
> login to the platform and start contributing there, instead of landing page. @kapilG0

Oh ok thanks you for guidance
