### ISSUE TITLE
Offers section need to be responsive 

### ISSUE THREAD

**Issue by kapilG0** [SnipSavvy/SnipSavvy_Frontend#46]
![Screenshot_20240602_161832](https://github.com/SnipSavvy/SnipSavvy_Frontend/assets/59639410/6008a66e-3458-488f-9da5-c0ba0ce04d5e)

**Comment by kapilG0** [comment]
Hello @SnipSavvy please assign this issue to me under ssoc 24

**Comment by sahilrohera10** [comment]
Focus on internal tool for SSOC @kapilG0
