### ISSUE TITLE
Adding ToolTips to Share, Edit and Copy Buttons on Hover

### ISSUE THREAD

**Issue by Aryan741x** [SnipSavvy/SnipSavvy_Frontend#50]
![image](https://github.com/SnipSavvy/SnipSavvy_Frontend/assets/128162387/ee44e0c5-6da0-4185-9deb-9613f2053d95)
Hello @sahilrohera10 I want to add this feature to the existing frontend for a better User experiance.
Kindly Assign this issue under SSOC 24

**Comment by cb7chaitanya** [comment]
Go for it, just keep the UI minimal and add a minimal Tootltip on hover, you can take a look at the tooltip you get on hovering over the workspace buttons

@Aryan741x 

Assigning you the issue, and send a small video when submitting for review, to see the hover effect in action

**Comment by yash-25log** [comment]
Merged PR
