### ISSUE TITLE
Adding tilt  effect to cards.

### ISSUE THREAD

**Issue by happyrao78** [SnipSavvy/SnipSavvy_Frontend#55]
Hi I'm a SSOC contributor and I would like to add the tilt  effect to all the cards present in home page for better user experience and feature credibility.
![Screenshot 2024-06-04 132339](https://github.com/SnipSavvy/SnipSavvy_Frontend/assets/138770813/c64fcf04-ff05-4460-a2b0-4557ba1a05bc)

**Comment by sahilrohera10** [comment]
hey @happyrao78 i encourage you to login into the platform and contribute to the internal tool for SSOC!
