### ISSUE TITLE
Bug : Improve Responsiveness of the Webpage and add Hamburger Menu

### ISSUE THREAD

**Issue by priyavratamohan** [SnipSavvy/SnipSavvy_Frontend#57]
**Problem -** On decreasing width dimensions of the Browser, the 'SnipSavvy' Logo image becomes heavily pixelated and appears blurry,
and the Navbar disappears.

_Screenshot of the problem -_ 

![image](https://github.com/SnipSavvy/SnipSavvy_Frontend/assets/91372958/642528ac-466a-4888-a753-78658940f23c)

**Solution -** I would like to keep the size of the 'SnipSavvy' Logo image constant when viewport width decreases, to eliminate the blurring problem.
And I would add a Hamburger Menu for the Navbar which appears when the width of the viewport decreases.

**Comment by Vrushti07** [comment]
I would like to work on it too, could please assign this to me too? Under SSOC?

**Comment by yash-25log** [comment]
We want you to contribute to the platform after signing up instead of the landing page @Vrushti07 @priyavratamohan 
All the best👍
