### ISSUE TITLE
The logo appears blurred at screen size below 1020px

### ISSUE THREAD

**Issue by snehagupta20** [SnipSavvy/SnipSavvy_Frontend#61]
When the screen size is smaller than 1020px, the logo becomes blurred.

https://github.com/SnipSavvy/SnipSavvy_Frontend/assets/92622110/64659888-3c92-48cf-9c7b-a8af03d0c0af

please assign this issue to me under SSOC.

**Comment by snehagupta20** [comment]
@yash-25log kindly assign this issue to me.

**Comment by yash-25log** [comment]
@snehagupta20 Since this is a desktop app, just skip responsive issues and try contributing to the platform after logging into it.
