### ISSUE TITLE
Move to top button alignment is not at correct position

### ISSUE THREAD

**Issue by AsifpMulla123** [SnipSavvy/SnipSavvy_Frontend#62]
Alignment of the move to top button is at center and its size is also large which is giving a bad user experience and also it hide the text

 Steps to solve the issue: 
  1. Align the move to top button to right side
  2. The width and height of the button is reduced
![Screenshot (196)](https://github.com/SnipSavvy/SnipSavvy_Frontend/assets/107197324/dbc82d11-1df7-4910-9bae-f921162588c4)

**Comment by AsifpMulla123** [comment]
please assign this issue to me

**Comment by yash-25log** [comment]
@AsifpMulla123 Since this is a desktop app , we just want you to skip responsive issues.
Just login to the platform and try contributing within it.
