### ISSUE TITLE
There is alignment issues in the SnipSavvy Offers sections  on screen size less than 763px

### ISSUE THREAD

**Issue by AsifpMulla123** [SnipSavvy/SnipSavvy_Frontend#63]
In SnipSavvy Offers sections on the screen size less than 763px the boxes or the contents are not responsive

How this issues is solved:
1.Apply media query to the mentioned screen size
2. change the width and height of the boxes 

Figure 1 👍

![Screenshot (197)](https://github.com/SnipSavvy/SnipSavvy_Frontend/assets/107197324/de533fa0-7cd7-4db4-a849-8950f0b36466)

Figure 2 👍 

![Screenshot (198)](https://github.com/SnipSavvy/SnipSavvy_Frontend/assets/107197324/94533ea5-24a2-4eeb-8ea9-242d362a2607)

**Comment by yash-25log** [comment]
@AsifpMulla123 This a desktop app. Just try to contribute to the platform after you login , instead of landing page . 👍
