### ISSUE TITLE
Add link tag in the Logo

### ISSUE THREAD

**Issue by tumansutradhar** [SnipSavvy/SnipSavvy_Frontend#68]
There is no link on the logo I want to add the link to the logo

**Comment by ManvendraPSdev** [comment]
Please Assign this issue to me

**Comment by tumansutradhar** [comment]
Oh! hello kindly find a new issue @ManvendraPSdev

**Comment by yash-25log** [comment]
@ManvendraPSdev @tumansutradhar we encourage you to contribute once you login to the platform, Instead of landing page.
